-- Ejecutar como SYS o DBA
CREATE USER APP_PYME IDENTIFIED BY "change_me" DEFAULT TABLESPACE USERS TEMPORARY TABLESPACE TEMP QUOTA UNLIMITED ON USERS;
GRANT CONNECT, RESOURCE TO APP_PYME;
-- Opcional: privilegio para crear sinónimos públicos si los usarás
-- GRANT CREATE PUBLIC SYNONYM TO APP_PYME;
GRANT CREATE VIEW TO APP_PYME;
