-- Conteos diarios de inventario (DDL puro)

CREATE TABLE conteo_inv_cab (
  id_conteo    NUMBER GENERATED BY DEFAULT AS IDENTITY,
  fecha        DATE NOT NULL,
  hora         VARCHAR2(8) NOT NULL,
  id_ubicacion NUMBER NOT NULL,
  responsable  VARCHAR2(100),
  confirmado   CHAR(1) DEFAULT 'N' NOT NULL CHECK (confirmado IN ('S','N')),
  creado_por   VARCHAR2(30),
  creado_en    TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT pk_conteo_inv_cab PRIMARY KEY (id_conteo)
);

ALTER TABLE conteo_inv_cab
  ADD CONSTRAINT fk_conteo_cab__ubicacion
  FOREIGN KEY (id_ubicacion) REFERENCES ubicacion(id_ubicacion);

CREATE TABLE conteo_inv_det (
  id_conteo   NUMBER NOT NULL,
  id_producto NUMBER NOT NULL,
  llenos      NUMBER DEFAULT 0 NOT NULL,
  vacios      NUMBER DEFAULT 0 NOT NULL,
  CONSTRAINT pk_conteo_inv_det PRIMARY KEY (id_conteo, id_producto)
);

ALTER TABLE conteo_inv_det
  ADD CONSTRAINT fk_conteo_det__cab
  FOREIGN KEY (id_conteo) REFERENCES conteo_inv_cab(id_conteo) ON DELETE CASCADE;

ALTER TABLE conteo_inv_det
  ADD CONSTRAINT fk_conteo_det__producto
  FOREIGN KEY (id_producto) REFERENCES producto(id_producto);
