-- Compras (solo DDL; la procedure va en 024_compras_proc.sql)

CREATE TABLE compra (
  id_compra            NUMBER GENERATED BY DEFAULT AS IDENTITY,
  nro_pedido           VARCHAR2(40),
  nro_factura          VARCHAR2(40),
  forma_pago           VARCHAR2(30),
  id_proveedor         NUMBER NOT NULL,
  fecha                DATE DEFAULT TRUNC(SYSDATE) NOT NULL,
  id_ubicacion_destino NUMBER NOT NULL,
  subtotal             NUMBER,
  iva                  NUMBER,
  total                NUMBER,
  CONSTRAINT pk_compra PRIMARY KEY (id_compra)
);

ALTER TABLE compra
  ADD CONSTRAINT fk_compra__proveedor
  FOREIGN KEY (id_proveedor) REFERENCES proveedor(id_proveedor);

ALTER TABLE compra
  ADD CONSTRAINT fk_compra__ubic_dest
  FOREIGN KEY (id_ubicacion_destino) REFERENCES ubicacion(id_ubicacion);

CREATE TABLE compra_det (
  id_compra          NUMBER NOT NULL,
  id_producto        NUMBER NOT NULL,
  cantidad           NUMBER NOT NULL,
  costo_unit_con_iva NUMBER,
  costo_unit_sin_iva NUMBER,
  CONSTRAINT pk_compra_det PRIMARY KEY (id_compra, id_producto)
);

ALTER TABLE compra_det
  ADD CONSTRAINT fk_compra_det__compra
  FOREIGN KEY (id_compra) REFERENCES compra(id_compra) ON DELETE CASCADE;

ALTER TABLE compra_det
  ADD CONSTRAINT fk_compra_det__producto
  FOREIGN KEY (id_producto) REFERENCES producto(id_producto);

CREATE INDEX ix_compra__nro_pedido  ON compra (nro_pedido);
CREATE INDEX ix_compra__nro_factura ON compra (nro_factura);
