-- Caja y cuentas

CREATE TABLE caja_mov (
  id          NUMBER GENERATED BY DEFAULT AS IDENTITY,
  fecha       TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  tipo        VARCHAR2(10) NOT NULL CHECK (tipo IN ('INGRESO','EGRESO')),
  medio_pago  VARCHAR2(15) NOT NULL CHECK (medio_pago IN ('EFECTIVO','TRANSFERENCIA','TARJETA')),
  monto       NUMBER(14,2) NOT NULL,
  ref_tipo    VARCHAR2(30),
  ref_id      NUMBER,
  observacion VARCHAR2(200),
  CONSTRAINT pk_caja_mov PRIMARY KEY (id)
);

CREATE TABLE cuenta_corriente (
  id     NUMBER GENERATED BY DEFAULT AS IDENTITY,
  banco  VARCHAR2(60) NOT NULL,
  numero VARCHAR2(60) NOT NULL,
  saldo  NUMBER(14,2) DEFAULT 0 NOT NULL,
  CONSTRAINT pk_cuenta_corriente PRIMARY KEY (id)
);

CREATE TABLE cta_cobrar (
  id_cc           NUMBER GENERATED BY DEFAULT AS IDENTITY,
  id_cliente      NUMBER NOT NULL,
  nro_factura     VARCHAR2(40),
  fecha_venta     DATE NOT NULL,
  plazo_dias      NUMBER DEFAULT 0 NOT NULL,
  direccion       VARCHAR2(200),
  telefono        VARCHAR2(60),
  monto_total     NUMBER(14,2) NOT NULL,
  saldo_pendiente NUMBER(14,2) NOT NULL,
  estado          VARCHAR2(10) DEFAULT 'ABIERTA' NOT NULL CHECK (estado IN ('ABIERTA','PAGADA','VENCIDA')),
  CONSTRAINT pk_cta_cobrar PRIMARY KEY (id_cc)
);

CREATE TABLE epp_mov (
  id        NUMBER GENERATED BY DEFAULT AS IDENTITY,
  fecha     TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  empleado  VARCHAR2(100) NOT NULL,
  recurso   VARCHAR2(100) NOT NULL,
  cantidad  NUMBER NOT NULL,
  tipo      VARCHAR2(10) NOT NULL CHECK (tipo IN ('ENTREGA','DEVOLUCION')),
  CONSTRAINT pk_epp_mov PRIMARY KEY (id)
);

ALTER TABLE cta_cobrar ADD CONSTRAINT fk_cta_cobrar__cliente FOREIGN KEY (id_cliente) REFERENCES cliente(id_cliente);

CREATE VIEW v_caja_saldo AS
SELECT medio_pago,
       SUM(CASE WHEN tipo = 'INGRESO' THEN monto ELSE -monto END) saldo
FROM caja_mov
GROUP BY medio_pago;

CREATE VIEW v_cta_cobrar_saldo AS
SELECT id_cliente,
       SUM(saldo_pendiente) saldo
FROM cta_cobrar
GROUP BY id_cliente;
