CREATE TABLE sucursal (
  id_sucursal     NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  nombre          VARCHAR2(100) NOT NULL,
  direccion       VARCHAR2(200),
  comuna          VARCHAR2(100),
  ciudad          VARCHAR2(100),
  activo          CHAR(1) DEFAULT 'S' CHECK (activo IN ('S','N')),
  fecha_creacion  TIMESTAMP DEFAULT SYSTIMESTAMP,
  creado_por      VARCHAR2(50) DEFAULT USER,
  CONSTRAINT pk_sucursal PRIMARY KEY (id_sucursal),
  CONSTRAINT uq_sucursal_nombre UNIQUE (nombre)
);

-- Extiende inventario para multi-sucursal (por simplicidad, 1 inventario por producto*sucursal)
ALTER TABLE inventario ADD (id_sucursal NUMBER);
ALTER TABLE inventario ADD CONSTRAINT fk_inv_sucursal
  FOREIGN KEY (id_sucursal) REFERENCES sucursal(id_sucursal);

-- Índices sugeridos
CREATE INDEX ix_inv__sucursal ON inventario(id_sucursal);

-- Sucursal por defecto + asignación de inventarios existentes a esa sucursal
DECLARE
  v_id NUMBER;
BEGIN
  INSERT INTO sucursal(nombre, direccion, ciudad) VALUES ('Casa Matriz', NULL, 'Santiago')
  RETURNING id_sucursal INTO v_id;

  UPDATE inventario SET id_sucursal = v_id WHERE id_sucursal IS NULL;
  COMMIT;
END;
/
