-- 1) Directorio para CSV (Windows: ajusta la ruta)
CREATE OR REPLACE DIRECTORY IMPORT_DIR AS 'C:\Users\ignac\Documents\Portafolio_Profesional\03_Bases_de_Datos\db-project\import';
GRANT READ, WRITE ON DIRECTORY IMPORT_DIR TO APP_PYME;

-- 2) External tables (campos como texto para tolerar formatos)
CREATE TABLE ext_proveedores (
  rut            VARCHAR2(30),
  razon_social   VARCHAR2(200),
  giro           VARCHAR2(200),
  telefono       VARCHAR2(50),
  email          VARCHAR2(200),
  direccion      VARCHAR2(300),
  activo         VARCHAR2(1)
)
ORGANIZATION EXTERNAL (
  TYPE ORACLE_LOADER
  DEFAULT DIRECTORY IMPORT_DIR
  ACCESS PARAMETERS (
    RECORDS DELIMITED BY NEWLINE
    FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
    SKIP 1
  )
  LOCATION ('proveedores.csv')
) REJECT LIMIT UNLIMITED;

CREATE TABLE ext_productos (
  sku           VARCHAR2(40),
  nombre        VARCHAR2(200),
  formato       VARCHAR2(10),
  unidad_medida VARCHAR2(10),
  costo         VARCHAR2(40),
  precio        VARCHAR2(40),
  imagen_url    VARCHAR2(300),
  activo        VARCHAR2(1)
)
ORGANIZATION EXTERNAL (
  TYPE ORACLE_LOADER
  DEFAULT DIRECTORY IMPORT_DIR
  ACCESS PARAMETERS (
    RECORDS DELIMITED BY NEWLINE
    FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
    SKIP 1
  )
  LOCATION ('productos.csv')
) REJECT LIMIT UNLIMITED;

CREATE TABLE ext_stock_inicial (
  sku            VARCHAR2(40),
  stock_actual   VARCHAR2(40),
  stock_minimo   VARCHAR2(40)
)
ORGANIZATION EXTERNAL (
  TYPE ORACLE_LOADER
  DEFAULT DIRECTORY IMPORT_DIR
  ACCESS PARAMETERS (
    RECORDS DELIMITED BY NEWLINE
    FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
    SKIP 1
  )
  LOCATION ('stock_inicial.csv')
) REJECT LIMIT UNLIMITED;

CREATE TABLE ext_clientes (
  rut         VARCHAR2(30),
  nombre      VARCHAR2(200),
  telefono    VARCHAR2(50),
  email       VARCHAR2(200),
  direccion   VARCHAR2(300),
  activo      VARCHAR2(1)
)
ORGANIZATION EXTERNAL (
  TYPE ORACLE_LOADER
  DEFAULT DIRECTORY IMPORT_DIR
  ACCESS PARAMETERS (
    RECORDS DELIMITED BY NEWLINE
    FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
    SKIP 1
  )
  LOCATION ('clientes.csv')
) REJECT LIMIT UNLIMITED;

CREATE TABLE ext_precios (
  sku   VARCHAR2(40),
  tipo  VARCHAR2(10),
  precio VARCHAR2(40)
)
ORGANIZATION EXTERNAL (
  TYPE ORACLE_LOADER
  DEFAULT DIRECTORY IMPORT_DIR
  ACCESS PARAMETERS (
    RECORDS DELIMITED BY NEWLINE
    FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
    SKIP 1
  )
  LOCATION ('precios.csv')
) REJECT LIMIT UNLIMITED;
