whenever sqlerror exit 1
whenever oserror exit 1
set define off
set sqlblanklines on
set serveroutput on

DECLARE
  v_tbl INTEGER;
  v_idx INTEGER;
BEGIN
  -- ¿existe la tabla?
  SELECT COUNT(*) INTO v_tbl
  FROM user_tables
  WHERE table_name = 'CLIENTES';

  IF v_tbl = 0 THEN
    EXECUTE IMMEDIATE q'[
      CREATE TABLE CLIENTES (
        ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
        RUT VARCHAR2(20) NOT NULL,
        NOMBRE VARCHAR2(120) NOT NULL,
        DIRECCION VARCHAR2(200),
        TELEFONO VARCHAR2(30),
        EMAIL VARCHAR2(120),
        CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP
      )
    ]';
  END IF;

  -- ¿existe el índice único?
  SELECT COUNT(*) INTO v_idx
  FROM user_indexes
  WHERE index_name = 'UX_CLIENTES_RUT';

  IF v_idx = 0 THEN
    EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX UX_CLIENTES_RUT ON CLIENTES(RUT)';
  END IF;
END;
/
prompt 001_init.sql DONE