name: API CI

on:
  push:
    branches: [ main, master, develop ]
    paths:
      - "apps/api/**"
      - ".github/workflows/ci.yml"
  pull_request:
    branches: [ main, master, develop ]
    paths:
      - "apps/api/**"
      - ".github/workflows/ci.yml"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  api:
    name: Lint & Build API (workspaces)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: |
            package-lock.json

      # Instala TODO con el lockfile del root respetando workspaces
      - name: Install deps (workspaces, include dev, omit optional)
        run: npm install --workspaces --include=dev --omit=optional --no-audit --no-fund

      # Ejecuta scripts en el workspace de la API
      - name: Type check
        run: npm run -w apps/api typecheck --if-present

      - name: Lint
        run: npm run -w apps/api lint --if-present

      - name: Build
        run: npm run -w apps/api build --if-present
