name: API CI

on:
  push:
    branches: [ main, master, develop ]
    paths:
      - "apps/api/**"
      - ".github/workflows/ci.yml"
  pull_request:
    branches: [ main, master, develop ]
    paths:
      - "apps/api/**"
      - ".github/workflows/ci.yml"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  api:
    name: Lint & Build API
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: apps/api

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: |
            apps/api/package-lock.json

      - name: Install deps (omit optional native deps)
        run: npm ci --omit=optional

      - name: TypeScript version
        run: npx tsc -v

      - name: Type check
        run: npm run typecheck --if-present

      - name: Lint
        run: npm run lint --if-present

      - name: Build
        run: npm run build --if-present
